### ISSUE TITLE
Slow loading with multiple thousands of contacts.

### ISSUE THREAD

**Issue by vekain** [broakenmedia/MultiContactPicker#27]

**Comment by broakenmedia** [comment]
Can you elaborate? If you close the picker, go into the phones contacts and add a new contact, re-opening the picker should reflect the new contact.

**Comment by vekain** [comment]
I mean to say that when there are 2000 or 3000 contacts available in the phonebook then while loading it starts hanging .. gets stuck to some while loop and background process and finally crashes.

**Comment by broakenmedia** [comment]
What type of loading are you using?

    .setLoadingType(MultiContactPicker.LOAD_ASYNC)

or 

   .setLoadingType(MultiContactPicker.LOAD_SYNC)

It may be worth experimenting with the other mode.

**Comment by vekain** [comment]
I am using the default loading type .... not giving anything. Also I think while loading your repo goes into background thread and stays there forever. After long process it just says to keep the app open or close it . I think instead of loading all the contacts you should find some alternative for multiple contact picking with intent opening contacts .... previously upto Android 6.0 it was working but now it doesn't support topdown intent type.

**Comment by broakenmedia** [comment]
Yeah it is definitely slower than ideal due to the fact it looks up the contact number + email on the initial load along with the names. It is extremely quick to just load the contact names. In order to improve performance it would require a refactor whereby when the user taps "finish" it then does a lookup for the numbers + emails of the only the selected contacts. I don't have time to do this currently and 2-3000 contacts is very unusual, typical even the most popular people only have around 600 contacts. That said, i have tested and confirmed the picker works into the thousands of contacts you simply need to keep waiting. Usually taking a minute or two.

**Comment by abhijith21198** [comment]
Hey i am a student and im trying to build the fingerprint atttendance system as my project.i got stuck in between and i found your priject. I was trying to refer your codes but it is very complex. Can you make me understand those or simplify it?
